### ISSUE TITLE
Aqua Security on Aws ubuntu Kubernetes cluster

### ISSUE THREAD

**Issue by vamsi1122** [aquasecurity/kube-bench#98]
Hello, I have created a kubernetes cluster using AWS Ubuntu, and i've run the aquasecurity kube bench to run the security check but i'm getting an error "**need apiserver executable but none of the candidates are running**". Can you please guide me on how to resolve the issue.

**Comment by ttousai** [comment]
Hello @vamsi1122 are you running kube-bench on a master node?

This error means that kube-bench could not detect a running kube-apiserver process. Please check the apiserver process is running on your node.

**Comment by vamsi1122** [comment]
I’m running in on the host machine and yes I’m checking for the master node. I’ve checked on multiple resources but couldn’t find how to check if api process is running ?

**Comment by ttousai** [comment]
@vamsi1122 how did you install kubernetes? It may be that our current implementation of kube-bench is not able to detect apiserver installed using that approach.

Also have you tried `ps -ef | grep apiserver`? It might show something interesting.

**Comment by ttousai** [comment]
@vamsi1122 can you share what output you got for `ps -ef | grep apiserver` please.

**Comment by jacobfoard** [comment]
Also having issues running on nodes, but that seems to be because they don't include kubectl on the nodes. 

To answer the above question:
```
$ ps -ef | grep apiserver
admin     4970  2342  0 21:47 pts/0    00:00:00 grep apiserver
```
My error however is:

```
$ ./kube-bench node

kubernetes version check failed: exec: "kubectl": executable file not found in $PATH
```

Any thoughts, or is kubectl necessary to be on the nodes for the tool to work?

**Comment by vamsi1122** [comment]
I had the similar error. You need to install kubectl on the nodes aswell.

**Comment by jacobfoard** [comment]
Installing kubectl fixed my issue. I wish it came preinstalled, but that an issue for the kops team.

**Comment by lizrice** [comment]
We've just made a change so that if kubectl isn't installed, the version will be obtained from kubelet. I think this should solve this issue - would be great if you could confirm whether this works for you @vamsi1122 @jacobfoard

**Comment by vamsi1122** [comment]
@lizrice I would like to run the Kube-Bench towards Openshift Container Platform. Do you see any possibility anytime soon?

**Comment by jacobfoard** [comment]
@lizrice I have confirmed this is working on my kops 1.8 cluster with out kubectl

**Comment by lizrice** [comment]
Thanks @jacobfoard. 

@vamsi1122 Regarding OpenShift, yes this is something we want to add support for - you might want to follow issue #23 (and we recently spoke to some folks from RedHat about this so hoping to make progress fairly soon)

**Comment by devops2201** [comment]
@lizrice kubectl logs kube-bench-node-xxxx
**need proxy executable but none of the candidates are running**

I am trying to run kube-bench on worker node (Virtual Machine Scale Set on Azure)
I am able to run kubectl commands from the worker node but I still see the above error.
Any help will be appreciated

**Comment by vamsi1122** [comment]
You need to run with a root permissions on the worker node

**Comment by devops2201** [comment]
@vamsi1122 I am running it as root

**Comment by vamsi1122** [comment]
I believe you have packages in master node please check whether having
packages on the worker nodes will work.
